title: Procedure Call
description: All things algorithms.

#markdown: kramdown
theme: minima #jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-katex

# any file in `_posts` directory gets a default layout of `post`
#defaults:
#  - scope:
#    path: _posts
#  - values:
#    layout: post

baseurl: ""
#url: "procedurecall.com"
